---

# create project
- name: check if project {{ project_name }} exists
  shell: "{{ openshift_cli }} get project {{ project_name }}"
  register: project_result
  ignore_errors: true
  changed_when: false

- name: create project {{ project_name }}
  shell: "{{ openshift_cli }} new-project {{ project_name }} --display-name='{{ project_display_name }}' --description='{{ project_desc }}'"
  when: project_result is failed

- name: assign user {{ project_admin }} as project admin in {{ project_name }}
  shell: "oc adm policy add-role-to-user admin {{ project_admin }} -n {{ project_name }}"
  ignore_errors: true
  when: >
    project_result is failed and
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != ""

- name: annotate project {{ project_name }}
  shell: "oc annotate --overwrite namespace {{ project_name }} {{ project_annotations }}"
  ignore_errors: true
  when: >
    project_result is failed and
    project_annotations is defined and
    project_annotations is not none and
    project_annotations|trim() != ""