---

# address-controller tls secret
- name: create '{{ crt_out }}' self-signed certificate
  shell: openssl req -new -x509 -batch -nodes -days 11000 -out {{ crt_out }} -keyout {{ key_out }} -subj "/O=io.enmasse/CN={{ crt_cn }}"
  
- name: create '{{ tls_secret_name }}' tls secret
  shell: |
    {{ openshift_cli }} create secret tls {{ tls_secret_name }} -n {{ project_name }} \
    --cert="{{ crt_out }}" --key="{{ key_out }}"
