---

# address-controller tls secret
- name: create self-signed certificate
  shell: openssl req -new -x509 -batch -nodes -days 11000 -out {{ crt_out }} -keyout {{ key_out }} -subj "/O=io.enmasse/CN={{ crt_cn }}"
  
- name: convert key to base64
  shell: echo $(base64 -w 0 {{ key_out }})
  register: tls_key_base64

- name: convert certificate to base64
  shell: echo $(base64 -w 0 {{ crt_out }})
  register: tls_crt_base64

- name: create tls secret from template
  template: src={{item}} dest={{ enmasse_tmp_dir }}/{{ tls_secret_name }}.json
  with_items:
    - tls-secret.json
  vars:
    tls_key: "{{ tls_key_base64.stdout }}"
    tls_crt: "{{ tls_crt_base64.stdout }}"

- name: deploy tls secret
  shell: |
     {{ openshift_cli }} create -f {{ enmasse_tmp_dir }}/{{ tls_secret_name }}.json \
        -n {{ project_name }}
